// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAixRPgxyf52w3y4mrJHIzLfG3mGYOtVdM',
    appId: '1:638261628234:web:077f1c0e1124ab4f0e85b3',
    messagingSenderId: '638261628234',
    projectId: 'spendly-194e0',
    authDomain: 'spendly-194e0.firebaseapp.com',
    storageBucket: 'spendly-194e0.firebasestorage.app',
    measurementId: 'G-07QEZ8FW6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAElPoMoWfte9__cNvlgSJZ1tugPs2fBRc',
    appId: '1:638261628234:android:94864f17200d725b0e85b3',
    messagingSenderId: '638261628234',
    projectId: 'spendly-194e0',
    storageBucket: 'spendly-194e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU4rL76a-XhYx9EU1MwR9EJqQhy6xHJYE',
    appId: '1:638261628234:ios:3174b2e33de7cc710e85b3',
    messagingSenderId: '638261628234',
    projectId: 'spendly-194e0',
    storageBucket: 'spendly-194e0.firebasestorage.app',
    iosClientId: '638261628234-uotddicji6u5dhargum54a2olvl9q11t.apps.googleusercontent.com',
    iosBundleId: 'com.example.spendly',
  );

}